# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Youth_Read(中青自动阅读AL)

on:
  workflow_dispatch:
  schedule:
     - cron: '20 */2 * * *'
  watch:
    types: Youth_Read
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ16: ${{ secrets.YOUTH_READ16 }}
      YOUTH_READ17: ${{ secrets.YOUTH_READ17 }}
      YOUTH_READ18: ${{ secrets.YOUTH_READ18 }}
      YOUTH_READ19: ${{ secrets.YOUTH_READ19 }}
      YOUTH_READ20: ${{ secrets.YOUTH_READ20 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ16
        run: |
          node Task/Youth_Read4.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ16 }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ17
        run: |
          node Task/Youth_Read4.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ17 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ18
        run: |
          node Task/Youth_Read4.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ18 }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ19
        run: |
          node Task/Youth_Read4.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ19 }}
          
      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ20
        run: |
          node Task/Youth_Read4.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ20 }}